### ISSUE TITLE
RL78/G13 FSL libraries Not found

### ISSUE THREAD

**Issue by RakeshVangaveti** [IARSystems/ewrl78-linker-config-flashlibs#4]
Hello,

We wanted to create Serial Bootloader for RL78/G13 - R5F100AC using One Image bootloader example in IAR Work Bench
[One Image Bootloader example RL78](https://www.renesas.com/us/en/document/apn/rl78-bootloader-one-image-r11an0470eu0100-rev100?language=en)
As you mentioned in [T01-FSL](https://www2.renesas.eu/products/micro/download/?oc=SelfLib_RL78#packageInfo) documentation, for FSL library configurations there is no such library found as fsl.a file instead I could see fsl.lib & fsl.inc files in downloaded FSL Type01 V3.00 from the Renesas website, As you suggested the V2.10 FSL libraries for this demo, those libraries are not available , Could you please provide us the source (FSL libraries which you have used in this demo)? we wanted to achieve the Flash routines (e.g. erase memory, read memory, write memory) of controller as initial step of bootloader

Thanks & Regards,
Rakesh Vangaveti,
vangavetrakesh@gmail.com

**Comment by ghost** [comment]
Dear Rakesh,

Thanks for your interest in this tutorial.

Application-specific design requirements (e.g., bootloader) or compilers other than the IAR Compiler for the Renesas RL78 are out of the tutorial’s scope. The tutorial was designed to help users with the IAR ILINK linker configuration for getting started using the Flash Libraries. We show how to get a remarkably simple [demo for the T01-FSL Library](https://github.com/IARSystems/ewrl78-linker-config-flashlibs/blob/master/t01-fsl.md) up and running from scratch.

The latest installer for the Renesas RL78 FSL ([FSL_RL78_Type01_Installer_V300.zip](https://www2.renesas.eu/products/micro/download/index.html/file/download/id/387/package/10704)) available at the time of this writing will provide an option:

- `[x] IAR Compiler version 2.10`

By installing the libraries using that option, you should get the `fsl.a` library and its associated headers, compatible with IAR Compiler v2+ for Renesas RL78.

All the Renesas RL78 Flash Libraries are distributed exclusively by Renesas Electronics so we could not include them in the demos.

If you need IAR Compiler support, you can reach out to fae@iar.com.

Let us know if you have further questions related to this thread, otherwise feel free to close the issue.

**Comment by RakeshVangaveti** [comment]
Hi @felipe-iar,

Thankyou for your immediate response!

Initially we have tried to generate the libraries by selecting Asia region, 
we can see the option which you mentioned by selecting Europe region and I'm able to generate the libraries with help of [FSL_RL78_Type01_Installer_V300.exe](https://www2.renesas.eu/products/micro/download/index.html/file/download/id/387/package/10704) 

We will definitely reach you incase we required further details regarding this tutorial.
Thanks & Regards,
Rakesh Vangaveti,
vangavetrakesh@gmail.com

**Comment by ghost** [comment]
Dear Rakesh,

Thank you for your feedback regarding the region selection issue.

I am glad you figured it out. I had no idea as I always went with the default selection.

I will write a note about it in the [Pre-requisites](https://github.com/IARSystems/ewrl78-linker-config-flashlibs/blob/master/README.md#pre-requisites) section of the tutorial, where the link to the Renesas Electronics Europe site is mentioned.

**Comment by RakeshVangaveti** [comment]
Hi @felipe-iar,
I believe there is no other configuration required for FSL integration in IAR other than you mentioned in this [T01 FSL Demo.](https://github.com/IARSystems/ewrl78-linker-config-flashlibs/blob/master/t01-fsl.md)

Thanks & Regards ,
Rakesh Vangaveti,
vangavetrakesh@gmail.com
